<?php
/**
 * @file context_flag.module
 * Main module file for the context_flag module.
 */

/**
 * Implements hook_context_plugins().
 */
function context_flag_context_plugins() {
  $plugins = array();
  $path = drupal_get_path('module', 'context_flag') . 'conditions/';
  // Plugins: Node Flags
  $plugins['node_active'] = array(
    'handler' => array(
      'path' => $path,
      'file' => 'context_flag_condition.node.inc',
      'class' => 'node_active',
      'parent' => 'context_condition',
    ),
  );
  $plugins['node_inactive'] = array(
    'handler' => array(
      'path' => $path,
      'file' => 'context_flag_condition.node.inc',
      'class' => 'node_inactive',
      'parent' => 'context_condition',
    ),
  );
  // Plugins: User Page Flags
  $plugins['user_page_active'] = array(
    'handler' => array(
      'path' => $path,
      'file' => 'context_flag_condition.user.inc',
      'class' => 'user_page_active',
      'parent' => 'context_condition',
    ),
  );
  $plugins['user_page_inactive'] = array(
    'handler' => array(
      'path' => $path,
      'file' => 'context_flag_condition.user.inc',
      'class' => 'user_page_inactive',
      'parent' => 'context_condition',
    ),
  );
  // Plugins: User Account Flags
  $plugins['user_account_active'] = array(
    'handler' => array(
      'path' => $path,
      'file' => 'context_flag_condition.user.inc',
      'class' => 'user_account_active',
      'parent' => 'context_condition',
    ),
  );
  $plugins['user_account_inactive'] = array(
    'handler' => array(
      'path' => $path,
      'file' => 'context_flag_condition.user.inc',
      'class' => 'user_account_inactive',
      'parent' => 'context_condition',
    ),
  );
  return $plugins;
}

/**
 * Implements hook_context_registry().
 */
function context_flag_context_registry() {
  return array(
    'conditions' => array(
      // Node conditions
      'node_active' => array(
        'title' => 'Node flag active',
        'description' => t('Enable this context when this Flag is active.'),
        'plugin' => 'node_active',
      ),
      'node_inactive' => array(
        'title' => 'Node flag inactive',
        'description' => t('Enable this context when this Flag is inactive.'),
        'plugin' => 'node_inactive',
      ),
      // User page conditions
      'user_page_active' => array(
        'title' => 'User page - flag active',
        'description' => t('Enable this context when viewing a user profile and this Flag is active.'),
        'plugin' => 'user_page_active',
      ),
      'user_page_inactive' => array(
        'title' => 'User page - flag inactive',
        'description' => t('Enable this context when viewing a user profile and this Flag is inactive.'),
        'plugin' => 'user_page_inactive',
      ),
      // User account conditions
      'user_account_active' => array(
        'title' => 'Current user - flag active',
        'description' => t('Enable this context when this flag is active for the currently logged-in user.'),
        'plugin' => 'user_account_active',
      ),
      'user_account_inactive' => array(
        'title' => 'Current user - flag inactive',
        'description' => t('Enable this context when this flag is inactive for the currently logged-in user.'),
        'plugin' => 'user_account_inactive',
      ),
    ),
  );
}

/**
 * Implements hook_context_page_condition().
 */
function context_flag_context_page_condition() {
  // Node conditions
  if ($plugin = context_get_plugin('condition', 'node_active')) {
    $plugin->execute();
  }
  if ($plugin = context_get_plugin('condition', 'node_inactive')) {
    $plugin->execute();
  }
  // User page conditions
  if ($plugin = context_get_plugin('condition', 'user_page_active')) {
    $plugin->execute();
  }
  if ($plugin = context_get_plugin('condition', 'user_page_inactive')) {
    $plugin->execute();
  }
  // User account conditions
  if ($plugin = context_get_plugin('condition', 'user_account_active')) {
    global $user;
    $plugin->execute($user);
  }
  if ($plugin = context_get_plugin('condition', 'user_account_inactive')) {
    global $user;
    $plugin->execute($user);
  }
}