<?php
/**
 * @file context_flag.module
 * Main module file for the context_flag module.
 */

/**
 * Implements hook_context_plugins().
 */
function context_flag_context_plugins() {
  $plugins = array();
  $path = drupal_get_path('module', 'context_flag') . 'conditions/';
  // Plugins: Node Flags
  $plugins['node_active'] = array(
    'handler' => array(
      'path' => $path,
      'file' => 'context_flag_condition.node.inc',
      'class' => 'node_active',
      'parent' => 'context_condition',
    ),
  );
  $plugins['node_inactive'] = array(
    'handler' => array(
      'path' => $path,
      'file' => 'context_flag_condition.node.inc',
      'class' => 'node_inactive',
      'parent' => 'context_condition',
    ),
  );
  return $plugins;
}

/**
 * Implements hook_context_registry().
 */
function context_flag_context_registry() {
  return array(
    'conditions' => array(
      'node_active' => array(
        'title' => 'Node Flag Active',
        'description' => t('Enable this context when this Flag is active.'),
        'plugin' => 'node_active',
      ),
      'node_inactive' => array(
        'title' => 'Node Flag Inactive',
        'description' => t('Enable this context when this Flag is inactive.'),
        'plugin' => 'node_inactive',
      ),
    ),
  );
}

/**
 * Implements hook_context_page_condition().
 */
function context_flag_context_page_condition() {
  if ($plugin = context_get_plugin('condition', 'node_active')) {
    $plugin->execute();
  }
  if ($plugin = context_get_plugin('condition', 'node_inactive')) {
    $plugin->execute();
  }
}